apiVersion: v1
kind: Service
metadata:
  name: tasksfrontendservice
spec:
  selector:
    app: tasksfrontendlabel
  type: LoadBalancer
  ports:
    - name: tasksfrontendport
      port: 80
      targetPort: 5000
  externalIPs:
    - 192.168.64.3
